# Generated by Django 3.2.16 on 2025-11-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_master_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='is_contact_phone',
            field=models.BooleanField(default=False, help_text='Общий номер для клиентов.', verbose_name='Телефон для справок'),
        ),
    ]
