# Generated by Django 3.2.16 on 2025-11-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_master_is_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='is_contact_phone',
            field=models.BooleanField(default=False, help_text='Использовать этот телефон для уведомлений клиентов (работает даже если мастер не активен)', verbose_name='Телефон для справок'),
        ),
    ]
