# Generated by Django 3.2.16 on 2025-11-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content_images/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('position', models.CharField(choices=[('mechanisms', 'Для механизмов действия'), ('problems', 'Для решаемых проблем'), ('advantages', 'Для преимуществ'), ('stages', 'Для этапов процедуры'), ('general', 'Общее изображение')], default='general', max_length=20, verbose_name='Позиция')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homepage.homepagecontent', verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Изображение контента',
                'verbose_name_plural': 'Изображения контента',
                'ordering': ['position', 'order'],
            },
        ),
    ]
