# Generated by Django 3.2.16 on 2025-11-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='procedures/', verbose_name='Фото процедуры'),
        ),
    ]
