# Generated by Django 3.2.16 on 2025-11-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер')),
                ('chat_id', models.CharField(max_length=50, verbose_name='Chat ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Chat клиента',
                'verbose_name_plural': 'Chats клиентов',
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название бота')),
                ('token', models.CharField(max_length=200, verbose_name='Токен бота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный бот')),
            ],
            options={
                'verbose_name': 'Telegram бот',
                'verbose_name_plural': 'Telegram боты',
            },
        ),
    ]
