# Generated by Django 3.2.16 on 2025-11-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_address_map_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_display_address',
            field=models.BooleanField(default=False, help_text='Использовать этот адрес на страницах сайта (about)', verbose_name='Адрес для отображения'),
        ),
        migrations.AddField(
            model_name='address',
            name='is_legal_address',
            field=models.BooleanField(default=False, help_text='Использовать этот адрес для юридических документов и согласий', verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
    ]
