# Generated by Django 3.2.16 on 2025-11-03 19:26

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название категории')),
                ('short_description', models.CharField(blank=True, help_text='До 30 символов для списка категорий', max_length=30, verbose_name='Короткое описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название процедуры')),
                ('short_description', models.CharField(help_text='До 30 символов (будет показано в списке)', max_length=30, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Продолжительность')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Цена')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна для записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
                'ordering': ['title'],
            },
        ),
    ]
