# Generated by Django 3.2.16 on 2025-11-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20251111_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='notification_method',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], default='email', max_length=10, verbose_name='Способ уведомления'),
        ),
    ]
