# Generated by Django 3.2.16 on 2025-11-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20251111_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_hours', models.PositiveIntegerField(default=24, help_text='За сколько часов до записи отправлять напоминание с подтверждением', verbose_name='За сколько часов напоминать')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активные настройки')),
            ],
            options={
                'verbose_name': 'Настройка напоминаний',
                'verbose_name_plural': 'Настройки напоминаний',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='needs_confirmation',
            field=models.BooleanField(default=True, verbose_name='Требует подтверждения'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Напоминание отправлено'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда отправлено напоминание'),
        ),
    ]
