# Generated by Django 3.2.16 on 2025-11-03 19:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Добро пожаловать в наш салон!', max_length=200, verbose_name='Заголовок страницы')),
                ('main_description', models.TextField(help_text='Основной текст под заголовком', verbose_name='Основное описание')),
                ('service_title', models.CharField(default='Массаж R-sleek – коррекция фигуры', max_length=200, verbose_name='Заголовок услуги')),
                ('service_description', models.TextField(help_text='Подробное описание основной услуги', verbose_name='Описание услуги')),
                ('how_it_works', models.TextField(help_text='Описание механизма работы процедуры', verbose_name='Как работает процедура?')),
                ('mechanisms', models.TextField(help_text='Основные механизмы действия (каждый пункт с новой строки)', verbose_name='Механизмы действия')),
                ('features', models.TextField(help_text='Особенности аппаратного массажа', verbose_name='Особенности массажа')),
                ('problems', models.TextField(help_text='Проблемы, с которыми справляется массаж (каждый пункт с новой строки)', verbose_name='Решаемые проблемы')),
                ('stages', models.TextField(help_text='Описание этапов процедуры', verbose_name='Этапы процедуры')),
                ('advantages', models.TextField(help_text='Преимущества массажа (каждый пункт с новой строки)', verbose_name='Преимущества')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('8000.00'), max_digits=10, verbose_name='Цена за сеанс')),
                ('price_description', models.TextField(default='Высококлассные специалисты, безопасность и привлекательные цены', verbose_name='Описание цены')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Контент главной страницы',
                'verbose_name_plural': 'Контент главной страницы',
            },
        ),
    ]
