# Generated by Django 3.2.16 on 2025-11-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='age',
            field=models.IntegerField(blank=True, default=25, verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
