# Client field lengths
CLIENT_PHONE_MAX_LENGTH = 20
CLIENT_NAME_MAX_LENGTH = 100
CLIENT_NOTIFICATION_METHOD_MAX_LENGTH = 10

# Client notification methods
CLIENT_NOTIFICATION_TELEGRAM = 'telegram'
CLIENT_NOTIFICATION_EMAIL = 'email'

# Client choices
CLIENT_NOTIFICATION_CHOICES = [
    (CLIENT_NOTIFICATION_TELEGRAM, 'Telegram'),
    (CLIENT_NOTIFICATION_EMAIL, 'Email'),
]

# Payment settings
PAYMENT_PHONE_MAX_LENGTH = 20
PAYMENT_PREPAYMENT_PERCENT_DEFAULT = 100

# User field lengths
USER_PHONE_MAX_LENGTH = 20
