# Generated by Django 3.2.16 on 2025-11-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='admin_chat_id',
            field=models.CharField(blank=True, help_text='ID чата для уведомлений администратора', max_length=50, verbose_name='Chat ID администратора'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='name',
            field=models.CharField(default='Основной бот', max_length=100, verbose_name='Название бота'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Токен бота'),
        ),
    ]
