# Generated by Django 3.2.16 on 2025-11-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новый клиент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_phone', models.CharField(max_length=20, verbose_name='Телефон администратора для оплаты')),
                ('master_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон мастера для оплаты')),
                ('prepayment_percent', models.PositiveIntegerField(default=100, verbose_name='Процент предоплаты для новых клиентов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активные настройки')),
            ],
            options={
                'verbose_name': 'Настройка оплаты',
                'verbose_name_plural': 'Настройки оплаты',
            },
        ),
    ]
