# Generated by Django 3.2.16 on 2025-11-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_client_paymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='always_prepayment',
            field=models.BooleanField(default=False, verbose_name='Всегда требовать предоплату'),
        ),
    ]
