# Generated by Django 3.2.16 on 2025-11-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_client_always_prepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='notification_method',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], default='telegram', max_length=10, verbose_name='Способ уведомления'),
        ),
    ]
