# Generated by Django 3.2.16 on 2025-11-03 22:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID брони')),
                ('booking_date', models.DateField(blank=True, null=True, verbose_name='Дата записи')),
                ('booking_time', models.TimeField(blank=True, null=True, verbose_name='Время записи')),
                ('client_phone', models.CharField(default='', max_length=20, verbose_name='Телефон клиента')),
                ('client_name', models.CharField(default='', max_length=100, verbose_name='Имя клиента')),
                ('client_telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram клиента')),
                ('personal_data_agreement', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('status', models.CharField(choices=[('pending', '⏳ Ожидает подтверждения'), ('confirmed', '✅ Подтверждено'), ('completed', '✅ Завершено'), ('cancelled', '❌ Отменено'), ('paid', '💰 Оплачено'), ('no_show', '🚫 Не пришел')], default='pending', max_length=25, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено')),
                ('telegram_message_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID сообщения в Telegram')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
