# Generated by Django 3.2.16 on 2025-11-03 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('catalog', '0002_procedure_image'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.master', verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='booking',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.procedure', verbose_name='Процедура'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'booking_time', 'master'], name='booking_boo_booking_ab35bc_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client_phone'], name='booking_boo_client__7fbafb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_boo_status_e01616_idx'),
        ),
    ]
