# Generated by Django 3.2.16 on 2025-11-03 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('catalog', '0002_procedure_image'),
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.procedure', verbose_name='Процедура'),
        ),
    ]
