# Generated by Django 3.2.16 on 2025-11-04 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20251104_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHoursSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(10, 0), verbose_name='Начало рабочего дня')),
                ('end_time', models.TimeField(default=datetime.time(20, 0), verbose_name='Конец рабочего дня')),
                ('time_interval', models.PositiveIntegerField(default=15, verbose_name='Интервал между записями (минуты)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активные настройки')),
            ],
            options={
                'verbose_name': 'Настройка рабочего времени',
                'verbose_name_plural': 'Настройки рабочего времени',
            },
        ),
    ]
