# Generated by Django 3.2.16 on 2025-11-04 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_client_paymentsettings'),
        ('booking', '0004_workinghourssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон для оплаты'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', '⏳ Ожидает оплаты'), ('paid', '✅ Оплачено'), ('not_required', '❌ Не требуется')], default='pending', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='booking',
            name='prepayment_required',
            field=models.BooleanField(default=False, verbose_name='Требуется предоплата'),
        ),
        migrations.AlterField(
            model_name='workinghourssettings',
            name='time_interval',
            field=models.PositiveIntegerField(default=30, help_text='Минимальный интервал в минутах (рекомендуется 30)', verbose_name='Минимальный интервал между записями (минуты)'),
        ),
    ]
