# Generated by Django 3.2.16 on 2025-11-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20251104_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Emailклиента'),
        ),
        migrations.AddField(
            model_name='booking',
            name='notification_method',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], default='telegram', max_length=10, verbose_name='Способ уведомления'),
        ),
    ]
