# Generated by Django 3.2.16 on 2025-11-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20251107_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client_telegram',
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email клиента'),
        ),
    ]
