# Generated by Django 3.2.16 on 2025-11-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='HTML код для встраивания карты (iframe)', verbose_name='Код для встраивания карты'),
        ),
    ]
